# Generated by Django 5.2.5 on 2025-08-30 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        help_text="Введите место, где выполняется привычка",
                        max_length=50,
                        verbose_name="Место, где выполняется привычка",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Укажите время выполнения привычки", verbose_name="Время выполнения привычки"
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        help_text="Введите действие", verbose_name="Действие, которое необходимо сделать"
                    ),
                ),
                ("is_nice_habit", models.BooleanField(default=False, verbose_name="Выбрать, если привычка приятная")),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения привычки(дни)",
                        validators=[
                            django.core.validators.MaxValueValidator(7),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.TextField(
                        blank=True,
                        help_text="Укажите награду после выполнения привычки",
                        null=True,
                        verbose_name="Награда после выполнения привычки",
                    ),
                ),
                (
                    "execute_time",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Укажите время выполнения привычки(секунды)",
                        validators=[
                            django.core.validators.MaxValueValidator(120),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Время выполнения(секунды)",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Выбрать для публикации в общий доступ"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="habits.habit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["id"],
            },
        ),
    ]
