# Generated by Django 5.2.5 on 2025-08-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_related_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="day_counter",
            field=models.PositiveIntegerField(default=1, verbose_name="Счетчик периодичности"),
        ),
    ]
